--!strict
return {
	["action.cancel"] = "Cancel",
	["action.confirm"] = "Confirm",
	
	["flake-info"] = "flake Information",
	["flake-info.name"] = "flake <font size=\"12\" color=\"#c8c8c8\">v{1.version}</font>",
	["flake-info.summary"] = "A simple, modern & experimental admin system.",
	["flake-info.addons"] = "This experience is using {1} addons:",
	
	["addon-info"] = "Addon Information",
	["addon-info.name"] = "{1.name} <font size=\"12\" color=\"#c8c8c8\">v{1.version}</font>",
	["addon-info.author"] = "Created by <b>{1.name}</b>",
	["addon-info.author2"] = "...and {1}.",
	["addon-info.extra"] = "    <b>ID:</b>  {1}        <b>Commands:</b>  {2}",
	
	["touch-menu"] = "flake menu",
	
	["command-bar"] = "Command Bar",
	["command-bar.type"] = "Type a command",
	["command-bar.info.true"] = "You may experience issues with typing on your device.",
	["command-bar.info.false"] = "Press TAB to use autocomplete (basic & prone to issues)",
	
	["command-list"] = "Available Commands",
	
	["addon-import"] = "Confirm Addon Import",
	["addon-import.body"] = "Are you sure you want to import <b>{1}</b>?<br/>The contained model may be dangerous!",
	
	["error.command"] = "Command Error",
	["error.addon-error"] = "Addon Error",
	["error.no-permission"] = "You do not have permission to run {1}.",
	["error.invalid-command"] = "{1} is not a valid command.",
	["error.addon-import-fail"] = "An unknown error occurred while loading {1}.",
	
	["notification.user-level-changed"] = "Permission level changed",
	["notification.user-level-changed.body"] = "Your level is now {1}."
}