--!strict
return {
	["action.cancel"] = "キャンセル",
	["action.confirm"] = "確認",
	
	["flake-info"] = "flake 情報",
	
	["addon-info"] = "アドオン情報",
	["addon-info.author"] = "によって作成された <b>{1.name}</b>",
	["addon-info.author2"] = "...と {1}",
	
	["touch-menu"] = "flake メニュー",
	
	["command-bar"] = "コマンドバー",
	
	["command-list"] = "利用可能なコマンド",
	
	["error.command"] = "コマンドエラー",
	["error.addon-error"] = "アドオン エラー"
}