--!strict
return {
	["action.cancel"] = "キャンセル",
	["action.confirm"] = "確認",
	
	["flake-info"] = "flake 情報",
	
	["addon-info"] = "アドオン情報",
	["addon-info.author"] = "によって作成された <b>{1.name}</b>",
	["addon-info.author2"] = "...と {1}",
	
	["touch-menu"] = "flake メニュー",
	
	["command-bar"] = "コマンドバー",
	
	["command-list"] = "利用可能なコマンド",
	
	["audit-log"] = "監査ログ",
	
	["audit-log-action.kick-player"] = "蹴った",
	["audit-log-action.import-addon"] = "インポートされたアドオン",
	
	["error.command"] = "コマンドエラー",
	["error.addon-error"] = "アドオン エラー",
	
	["argument-error.command"] = "その名前に一致するコマンドはありません",
	["argument-error.player-name"] = "その名前に一致するプレイヤーはいません",
	["argument-error.type-mismatch"] = "{1.id} は {1.type} でなければならない",
}