--!strict
return {
	primary = {
		color = {
			normal = Color3.fromRGB(50, 50, 50)
		},
		background = {
			hover = Color3.new(1, 1, 1),
			normal = Color3.new(0.9, 0.9, 0.9),
			active = Color3.new(1, 1, 1),
			disabled = Color3.new(0.6, 0.6, 0.6)
		}
	},
	secondary = {
		color = {
			hover = Color3.new(1, 1, 1),
			normal = Color3.new(0.9, 0.9, 0.9),
			disabled = Color3.new(0.6, 0.6, 0.6)
		},
		border = {
			hover = Color3.new(1, 1, 1),
			normal = Color3.new(0.9, 0.9, 0.9),
			active = Color3.new(1, 1, 1),
			disabled = Color3.new(0.6, 0.6, 0.6)
		},
		background = {
			hover = Color3.new(1, 1, 1),
			normal = Color3.new(1, 1, 1),
			active = Color3.new(1, 1, 1),
			disabled = Color3.new(1, 1, 1)
		},
		noBackground = true
	}
}