--!strict
return {
	TOUCH_MENU_BG = "rbxassetid://12782309588", --touch menu bg@2x.png | 432x96,
	
	FLAKE_ICON = "rbxassetid://12782343310", --icon@2x.png | 128x128,
	COMMAND_BAR_ICON = "rbxassetid://12782324394", --flake command bar@2x.png | 80x80,
	
	PLACEHOLDER_ICON = "rbxassetid://12782863561", --addon icon@2x.png | 128x128
	PLACEHOLDER_ICON2 = "rbxassetid://12782864342" --addon icon 2@2x.png | 80x80
}